language: rust
sudo: required
rust:
- stable
script:
- cargo build
- cargo test
- cargo bench
- cargo doc
- for file in $(find mdbook -name '*.md'); do rustdoc --test $file  -L ./target/debug/deps; done
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo install mdbook &&
  (cd mdbook; mdbook build) &&
  sudo pip install ghp-import &&
  ghp-import -n mdbook/book &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
  - secure: CzDrbiXWbvgjqZn1z5aFcttW90tWT4LpEc9bSJ/Wb0i4QvABAaOefw3Griu9MT9vNvbyM1ysk8fzXMHXF1ivhUZFzV4MRr+nrKg4LTg/upDAVAEOjWdrFUJOp17a+PVS3K83zrVxeZMkmQe4ACB3a9hsHilKp635xgizSJWQ6Wo=
